version: 0.2

phases:

  build:
    commands:
      - dotnet restore ./basic-web-app.csproj
      - dotnet build ./basic-web-app.csproj
      - dotnet publish ./basic-web-app.csproj -o ./
artifacts:
  files:
    - '**/*'
  base-directory: './'
  
