version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 2.2   
    commands:
      - dotnet tool install -g Amazon.ElasticBeanstalk.Tools
  build:
    commands:
      - cd deployment-app-csharp
      - dotnet eb package
artifacts:
  files:
    - ./basic-web-app.sln
  discard-paths: yes
  
